set shell=bash
set textwidth=72
set hlsearch
nmap s :exec "normal i".nr2char(getchar())."\e"<CR>
nmap S :exec "normal a".nr2char(getchar())."\e"<CR>
nmap <Space> :nohlsearch<Bar>echo<CR>
map <c-a> ^
map <c-e> $
