(custom-set litable-result-format "=> %s")

(setq litable-pure-functions-list
      (seq-difference litable-pure-functions-list
                      '(LaTeX-back-to-indentation
                        LaTeX-find-matching-begin
                        LaTeX-mark-environment
                        TeX-check-files
                        TeX-fold-mode
                        TeX-normal-mode
                        activate-mark
                        back-to-indentation
                        backward-char
                        backward-list
                        backward-sexp
                        backward-up-list
                        backward-word
                        beginning-of-buffer
                        beginning-of-defun
                        beginning-of-line
                        beginning-of-thing
                        c-end-of-defun
                        check-parens
                        completing-read
                        decf
                        dired-next-line
                        down-list
                        end-of-defun
                        end-of-line
                        end-of-thing
                        error
                        forward-char
                        forward-line
                        forward-list
                        forward-sexp
                        goto-char
                        goto-line
                        make-marker
                        make-overlay
                        message
                        move-beginning-of-line
                        move-end-of-line
                        move-overlay
                        overlay-put
                        paredit-backward-up
                        princ
                        print
                        re-search-backward
                        re-search-forward
                        remove-overlays
                        save-current-buffer
                        set
                        set-buffer
                        setf
                        setq
                        set-buffer-modified-p
                        signal
                        skip-chars-backward
                        skip-chars-forward
                        warn
                        y-or-n-p
                        yes-or-no-p)))
